---
- name: Deploy Scientific Calculator
  hosts: local
  become: false
  vars:
    docker_image_name: sriram9217/scientific-calculator
    docker_container_name: scientific-calculator
  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ docker_image_name }}:latest"
        source: pull
        state: present

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image_name }}:latest"
        state: started
        restart_policy: always
        ports:
          - "8081:80"

    - name: Check if container is running
      community.docker.docker_container_info:
        name: "{{ docker_container_name }}"
      register: container_info

    - name: Display container info
      debug:
        var: container_info.container.State.Running